//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PC.ServiceBus.Configuration
{
    
    
    /// <summary>
    /// The AzureConfiguration Configuration Section.
    /// </summary>
    public partial class AzureConfiguration : global::System.Configuration.ConfigurationSection
    {
        
        #region Singleton Instance
        /// <summary>
        /// The XML name of the AzureConfiguration Configuration Section.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        internal const string AzureConfigurationSectionName = "azureConfiguration";
        
        /// <summary>
        /// Gets the AzureConfiguration instance.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        public static global::PC.ServiceBus.Configuration.AzureConfiguration Instance
        {
            get
            {
                return ((global::PC.ServiceBus.Configuration.AzureConfiguration)(global::System.Configuration.ConfigurationManager.GetSection(global::PC.ServiceBus.Configuration.AzureConfiguration.AzureConfigurationSectionName)));
            }
        }
        #endregion
        
        #region Xmlns Property
        /// <summary>
        /// The XML name of the <see cref="Xmlns"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        internal const string XmlnsPropertyName = "xmlns";
        
        /// <summary>
        /// Gets the XML namespace of this Configuration Section.
        /// </summary>
        /// <remarks>
        /// This property makes sure that if the configuration file contains the XML namespace,
        /// the parser doesn't throw an exception because it encounters the unknown "xmlns" attribute.
        /// </remarks>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::PC.ServiceBus.Configuration.AzureConfiguration.XmlnsPropertyName, IsRequired=false, IsKey=false, IsDefaultCollection=false)]
        public string Xmlns
        {
            get
            {
                return ((string)(base[global::PC.ServiceBus.Configuration.AzureConfiguration.XmlnsPropertyName]));
            }
        }
        #endregion
        
        #region IsReadOnly override
        /// <summary>
        /// Gets a value indicating whether the element is read-only.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        public override bool IsReadOnly()
        {
            return false;
        }
        #endregion
        
        #region Settings Property
        /// <summary>
        /// The XML name of the <see cref="Settings"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        internal const string SettingsPropertyName = "settings";
        
        /// <summary>
        /// Gets or sets the Settings.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        [global::System.ComponentModel.DescriptionAttribute("The Settings.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::PC.ServiceBus.Configuration.AzureConfiguration.SettingsPropertyName, IsRequired=false, IsKey=false, IsDefaultCollection=false)]
        public virtual global::PC.ServiceBus.Configuration.Settings Settings
        {
            get
            {
                return ((global::PC.ServiceBus.Configuration.Settings)(base[global::PC.ServiceBus.Configuration.AzureConfiguration.SettingsPropertyName]));
            }
            set
            {
                base[global::PC.ServiceBus.Configuration.AzureConfiguration.SettingsPropertyName] = value;
            }
        }
        #endregion
        
        #region Topics Property
        /// <summary>
        /// The XML name of the <see cref="Topics"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        internal const string TopicsPropertyName = "topics";
        
        /// <summary>
        /// Gets or sets the Topics.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        [global::System.ComponentModel.DescriptionAttribute("The Topics.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::PC.ServiceBus.Configuration.AzureConfiguration.TopicsPropertyName, IsRequired=true, IsKey=false, IsDefaultCollection=false)]
        public virtual global::PC.ServiceBus.Configuration.topics Topics
        {
            get
            {
                return ((global::PC.ServiceBus.Configuration.topics)(base[global::PC.ServiceBus.Configuration.AzureConfiguration.TopicsPropertyName]));
            }
            set
            {
                base[global::PC.ServiceBus.Configuration.AzureConfiguration.TopicsPropertyName] = value;
            }
        }
        #endregion
    }
}
namespace PC.ServiceBus.Configuration
{
    
    
    /// <summary>
    /// A collection of Add instances.
    /// </summary>
    [global::System.Configuration.ConfigurationCollectionAttribute(typeof(global::PC.ServiceBus.Configuration.Add), CollectionType=global::System.Configuration.ConfigurationElementCollectionType.BasicMapAlternate, AddItemName=global::PC.ServiceBus.Configuration.Settings.AddPropertyName)]
    public partial class Settings : global::System.Configuration.ConfigurationElementCollection
    {
        
        #region Constants
        /// <summary>
        /// The XML name of the individual <see cref="global::PC.ServiceBus.Configuration.Add"/> instances in this collection.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        internal const string AddPropertyName = "add";
        #endregion
        
        #region Overrides
        /// <summary>
        /// Gets the type of the <see cref="global::System.Configuration.ConfigurationElementCollection"/>.
        /// </summary>
        /// <returns>The <see cref="global::System.Configuration.ConfigurationElementCollectionType"/> of this collection.</returns>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        public override global::System.Configuration.ConfigurationElementCollectionType CollectionType
        {
            get
            {
                return global::System.Configuration.ConfigurationElementCollectionType.BasicMapAlternate;
            }
        }
        
        /// <summary>
        /// Gets the name used to identify this collection of elements
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        protected override string ElementName
        {
            get
            {
                return global::PC.ServiceBus.Configuration.Settings.AddPropertyName;
            }
        }
        
        /// <summary>
        /// Indicates whether the specified <see cref="global::System.Configuration.ConfigurationElement"/> exists in the <see cref="global::System.Configuration.ConfigurationElementCollection"/>.
        /// </summary>
        /// <param name="elementName">The name of the element to verify.</param>
        /// <returns>
        /// <see langword="true"/> if the element exists in the collection; otherwise, <see langword="false"/>.
        /// </returns>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        protected override bool IsElementName(string elementName)
        {
            return (elementName == global::PC.ServiceBus.Configuration.Settings.AddPropertyName);
        }
        
        /// <summary>
        /// Gets the element key for the specified configuration element.
        /// </summary>
        /// <param name="element">The <see cref="global::System.Configuration.ConfigurationElement"/> to return the key for.</param>
        /// <returns>
        /// An <see cref="object"/> that acts as the key for the specified <see cref="global::System.Configuration.ConfigurationElement"/>.
        /// </returns>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        protected override object GetElementKey(global::System.Configuration.ConfigurationElement element)
        {
            return ((global::PC.ServiceBus.Configuration.Add)(element)).Key;
        }
        
        /// <summary>
        /// Creates a new <see cref="global::PC.ServiceBus.Configuration.Add"/>.
        /// </summary>
        /// <returns>
        /// A new <see cref="global::PC.ServiceBus.Configuration.Add"/>.
        /// </returns>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        protected override global::System.Configuration.ConfigurationElement CreateNewElement()
        {
            return new global::PC.ServiceBus.Configuration.Add();
        }
        #endregion
        
        #region Indexer
        /// <summary>
        /// Gets the <see cref="global::PC.ServiceBus.Configuration.Add"/> at the specified index.
        /// </summary>
        /// <param name="index">The index of the <see cref="global::PC.ServiceBus.Configuration.Add"/> to retrieve.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        public global::PC.ServiceBus.Configuration.Add this[int index]
        {
            get
            {
                return ((global::PC.ServiceBus.Configuration.Add)(base.BaseGet(index)));
            }
        }
        
        /// <summary>
        /// Gets the <see cref="global::PC.ServiceBus.Configuration.Add"/> with the specified key.
        /// </summary>
        /// <param name="key">The key of the <see cref="global::PC.ServiceBus.Configuration.Add"/> to retrieve.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        public global::PC.ServiceBus.Configuration.Add this[object key]
        {
            get
            {
                return ((global::PC.ServiceBus.Configuration.Add)(base.BaseGet(key)));
            }
        }
        #endregion
        
        #region Add
        /// <summary>
        /// Adds the specified <see cref="global::PC.ServiceBus.Configuration.Add"/> to the <see cref="global::System.Configuration.ConfigurationElementCollection"/>.
        /// </summary>
        /// <param name="add">The <see cref="global::PC.ServiceBus.Configuration.Add"/> to add.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        public void Add(global::PC.ServiceBus.Configuration.Add add)
        {
            base.BaseAdd(add);
        }
        #endregion
        
        #region Remove
        /// <summary>
        /// Removes the specified <see cref="global::PC.ServiceBus.Configuration.Add"/> from the <see cref="global::System.Configuration.ConfigurationElementCollection"/>.
        /// </summary>
        /// <param name="add">The <see cref="global::PC.ServiceBus.Configuration.Add"/> to remove.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        public void Remove(global::PC.ServiceBus.Configuration.Add add)
        {
            base.BaseRemove(this.GetElementKey(add));
        }
        #endregion
        
        #region GetItem
        /// <summary>
        /// Gets the <see cref="global::PC.ServiceBus.Configuration.Add"/> at the specified index.
        /// </summary>
        /// <param name="index">The index of the <see cref="global::PC.ServiceBus.Configuration.Add"/> to retrieve.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        public global::PC.ServiceBus.Configuration.Add GetItemAt(int index)
        {
            return ((global::PC.ServiceBus.Configuration.Add)(base.BaseGet(index)));
        }
        
        /// <summary>
        /// Gets the <see cref="global::PC.ServiceBus.Configuration.Add"/> with the specified key.
        /// </summary>
        /// <param name="key">The key of the <see cref="global::PC.ServiceBus.Configuration.Add"/> to retrieve.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        public global::PC.ServiceBus.Configuration.Add GetItemByKey(string key)
        {
            return ((global::PC.ServiceBus.Configuration.Add)(base.BaseGet(((object)(key)))));
        }
        #endregion
        
        #region IsReadOnly override
        /// <summary>
        /// Gets a value indicating whether the element is read-only.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        public override bool IsReadOnly()
        {
            return false;
        }
        #endregion
    }
}
namespace PC.ServiceBus.Configuration
{
    
    
    /// <summary>
    /// The Add Configuration Element.
    /// </summary>
    public partial class Add : global::System.Configuration.ConfigurationElement
    {
        
        #region IsReadOnly override
        /// <summary>
        /// Gets a value indicating whether the element is read-only.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        public override bool IsReadOnly()
        {
            return false;
        }
        #endregion
        
        #region Key Property
        /// <summary>
        /// The XML name of the <see cref="Key"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        internal const string KeyPropertyName = "key";
        
        /// <summary>
        /// Gets or sets the Key.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        [global::System.ComponentModel.DescriptionAttribute("The Key.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::PC.ServiceBus.Configuration.Add.KeyPropertyName, IsRequired=true, IsKey=true, IsDefaultCollection=false)]
        public virtual string Key
        {
            get
            {
                return ((string)(base[global::PC.ServiceBus.Configuration.Add.KeyPropertyName]));
            }
            set
            {
                base[global::PC.ServiceBus.Configuration.Add.KeyPropertyName] = value;
            }
        }
        #endregion
        
        #region Value Property
        /// <summary>
        /// The XML name of the <see cref="Value"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        internal const string ValuePropertyName = "value";
        
        /// <summary>
        /// Gets or sets the Value.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        [global::System.ComponentModel.DescriptionAttribute("The Value.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::PC.ServiceBus.Configuration.Add.ValuePropertyName, IsRequired=false, IsKey=false, IsDefaultCollection=false)]
        public virtual string Value
        {
            get
            {
                return ((string)(base[global::PC.ServiceBus.Configuration.Add.ValuePropertyName]));
            }
            set
            {
                base[global::PC.ServiceBus.Configuration.Add.ValuePropertyName] = value;
            }
        }
        #endregion
    }
}
namespace PC.ServiceBus.Configuration
{
    
    
    /// <summary>
    /// A collection of topic instances.
    /// </summary>
    [global::System.Configuration.ConfigurationCollectionAttribute(typeof(global::PC.ServiceBus.Configuration.topic), CollectionType=global::System.Configuration.ConfigurationElementCollectionType.BasicMapAlternate, AddItemName=global::PC.ServiceBus.Configuration.topics.topicPropertyName)]
    public partial class topics : global::System.Configuration.ConfigurationElementCollection
    {
        
        #region Constants
        /// <summary>
        /// The XML name of the individual <see cref="global::PC.ServiceBus.Configuration.topic"/> instances in this collection.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        internal const string topicPropertyName = "topic";
        #endregion
        
        #region Overrides
        /// <summary>
        /// Gets the type of the <see cref="global::System.Configuration.ConfigurationElementCollection"/>.
        /// </summary>
        /// <returns>The <see cref="global::System.Configuration.ConfigurationElementCollectionType"/> of this collection.</returns>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        public override global::System.Configuration.ConfigurationElementCollectionType CollectionType
        {
            get
            {
                return global::System.Configuration.ConfigurationElementCollectionType.BasicMapAlternate;
            }
        }
        
        /// <summary>
        /// Gets the name used to identify this collection of elements
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        protected override string ElementName
        {
            get
            {
                return global::PC.ServiceBus.Configuration.topics.topicPropertyName;
            }
        }
        
        /// <summary>
        /// Indicates whether the specified <see cref="global::System.Configuration.ConfigurationElement"/> exists in the <see cref="global::System.Configuration.ConfigurationElementCollection"/>.
        /// </summary>
        /// <param name="elementName">The name of the element to verify.</param>
        /// <returns>
        /// <see langword="true"/> if the element exists in the collection; otherwise, <see langword="false"/>.
        /// </returns>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        protected override bool IsElementName(string elementName)
        {
            return (elementName == global::PC.ServiceBus.Configuration.topics.topicPropertyName);
        }
        
        /// <summary>
        /// Gets the element key for the specified configuration element.
        /// </summary>
        /// <param name="element">The <see cref="global::System.Configuration.ConfigurationElement"/> to return the key for.</param>
        /// <returns>
        /// An <see cref="object"/> that acts as the key for the specified <see cref="global::System.Configuration.ConfigurationElement"/>.
        /// </returns>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        protected override object GetElementKey(global::System.Configuration.ConfigurationElement element)
        {
            return ((global::PC.ServiceBus.Configuration.topic)(element)).name;
        }
        
        /// <summary>
        /// Creates a new <see cref="global::PC.ServiceBus.Configuration.topic"/>.
        /// </summary>
        /// <returns>
        /// A new <see cref="global::PC.ServiceBus.Configuration.topic"/>.
        /// </returns>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        protected override global::System.Configuration.ConfigurationElement CreateNewElement()
        {
            return new global::PC.ServiceBus.Configuration.topic();
        }
        #endregion
        
        #region Indexer
        /// <summary>
        /// Gets the <see cref="global::PC.ServiceBus.Configuration.topic"/> at the specified index.
        /// </summary>
        /// <param name="index">The index of the <see cref="global::PC.ServiceBus.Configuration.topic"/> to retrieve.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        public global::PC.ServiceBus.Configuration.topic this[int index]
        {
            get
            {
                return ((global::PC.ServiceBus.Configuration.topic)(base.BaseGet(index)));
            }
        }
        
        /// <summary>
        /// Gets the <see cref="global::PC.ServiceBus.Configuration.topic"/> with the specified key.
        /// </summary>
        /// <param name="name">The key of the <see cref="global::PC.ServiceBus.Configuration.topic"/> to retrieve.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        public global::PC.ServiceBus.Configuration.topic this[object name]
        {
            get
            {
                return ((global::PC.ServiceBus.Configuration.topic)(base.BaseGet(name)));
            }
        }
        #endregion
        
        #region Add
        /// <summary>
        /// Adds the specified <see cref="global::PC.ServiceBus.Configuration.topic"/> to the <see cref="global::System.Configuration.ConfigurationElementCollection"/>.
        /// </summary>
        /// <param name="topic">The <see cref="global::PC.ServiceBus.Configuration.topic"/> to add.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        public void Add(global::PC.ServiceBus.Configuration.topic topic)
        {
            base.BaseAdd(topic);
        }
        #endregion
        
        #region Remove
        /// <summary>
        /// Removes the specified <see cref="global::PC.ServiceBus.Configuration.topic"/> from the <see cref="global::System.Configuration.ConfigurationElementCollection"/>.
        /// </summary>
        /// <param name="topic">The <see cref="global::PC.ServiceBus.Configuration.topic"/> to remove.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        public void Remove(global::PC.ServiceBus.Configuration.topic topic)
        {
            base.BaseRemove(this.GetElementKey(topic));
        }
        #endregion
        
        #region GetItem
        /// <summary>
        /// Gets the <see cref="global::PC.ServiceBus.Configuration.topic"/> at the specified index.
        /// </summary>
        /// <param name="index">The index of the <see cref="global::PC.ServiceBus.Configuration.topic"/> to retrieve.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        public global::PC.ServiceBus.Configuration.topic GetItemAt(int index)
        {
            return ((global::PC.ServiceBus.Configuration.topic)(base.BaseGet(index)));
        }
        
        /// <summary>
        /// Gets the <see cref="global::PC.ServiceBus.Configuration.topic"/> with the specified key.
        /// </summary>
        /// <param name="name">The key of the <see cref="global::PC.ServiceBus.Configuration.topic"/> to retrieve.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        public global::PC.ServiceBus.Configuration.topic GetItemByKey(string name)
        {
            return ((global::PC.ServiceBus.Configuration.topic)(base.BaseGet(((object)(name)))));
        }
        #endregion
        
        #region IsReadOnly override
        /// <summary>
        /// Gets a value indicating whether the element is read-only.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        public override bool IsReadOnly()
        {
            return false;
        }
        #endregion
    }
}
namespace PC.ServiceBus.Configuration
{
    
    
    /// <summary>
    /// The subscription Configuration Element.
    /// </summary>
    public partial class subscription : global::System.Configuration.ConfigurationElement
    {
        
        #region IsReadOnly override
        /// <summary>
        /// Gets a value indicating whether the element is read-only.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        public override bool IsReadOnly()
        {
            return false;
        }
        #endregion
        
        #region name Property
        /// <summary>
        /// The XML name of the <see cref="name"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        internal const string namePropertyName = "name";
        
        /// <summary>
        /// Gets or sets the name.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        [global::System.ComponentModel.DescriptionAttribute("The name.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::PC.ServiceBus.Configuration.subscription.namePropertyName, IsRequired=true, IsKey=true, IsDefaultCollection=false)]
        public virtual string name
        {
            get
            {
                return ((string)(base[global::PC.ServiceBus.Configuration.subscription.namePropertyName]));
            }
            set
            {
                base[global::PC.ServiceBus.Configuration.subscription.namePropertyName] = value;
            }
        }
        #endregion
    }
}
namespace PC.ServiceBus.Configuration
{
    
    
    /// <summary>
    /// A collection of subscription instances.
    /// </summary>
    [global::System.Configuration.ConfigurationCollectionAttribute(typeof(global::PC.ServiceBus.Configuration.subscription), CollectionType=global::System.Configuration.ConfigurationElementCollectionType.BasicMapAlternate, AddItemName=global::PC.ServiceBus.Configuration.topic.subscriptionPropertyName)]
    public partial class topic : global::System.Configuration.ConfigurationElementCollection
    {
        
        #region Constants
        /// <summary>
        /// The XML name of the individual <see cref="global::PC.ServiceBus.Configuration.subscription"/> instances in this collection.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        internal const string subscriptionPropertyName = "subscription";
        #endregion
        
        #region Overrides
        /// <summary>
        /// Gets the type of the <see cref="global::System.Configuration.ConfigurationElementCollection"/>.
        /// </summary>
        /// <returns>The <see cref="global::System.Configuration.ConfigurationElementCollectionType"/> of this collection.</returns>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        public override global::System.Configuration.ConfigurationElementCollectionType CollectionType
        {
            get
            {
                return global::System.Configuration.ConfigurationElementCollectionType.BasicMapAlternate;
            }
        }
        
        /// <summary>
        /// Gets the name used to identify this collection of elements
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        protected override string ElementName
        {
            get
            {
                return global::PC.ServiceBus.Configuration.topic.subscriptionPropertyName;
            }
        }
        
        /// <summary>
        /// Indicates whether the specified <see cref="global::System.Configuration.ConfigurationElement"/> exists in the <see cref="global::System.Configuration.ConfigurationElementCollection"/>.
        /// </summary>
        /// <param name="elementName">The name of the element to verify.</param>
        /// <returns>
        /// <see langword="true"/> if the element exists in the collection; otherwise, <see langword="false"/>.
        /// </returns>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        protected override bool IsElementName(string elementName)
        {
            return (elementName == global::PC.ServiceBus.Configuration.topic.subscriptionPropertyName);
        }
        
        /// <summary>
        /// Gets the element key for the specified configuration element.
        /// </summary>
        /// <param name="element">The <see cref="global::System.Configuration.ConfigurationElement"/> to return the key for.</param>
        /// <returns>
        /// An <see cref="object"/> that acts as the key for the specified <see cref="global::System.Configuration.ConfigurationElement"/>.
        /// </returns>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        protected override object GetElementKey(global::System.Configuration.ConfigurationElement element)
        {
            return ((global::PC.ServiceBus.Configuration.subscription)(element)).name;
        }
        
        /// <summary>
        /// Creates a new <see cref="global::PC.ServiceBus.Configuration.subscription"/>.
        /// </summary>
        /// <returns>
        /// A new <see cref="global::PC.ServiceBus.Configuration.subscription"/>.
        /// </returns>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        protected override global::System.Configuration.ConfigurationElement CreateNewElement()
        {
            return new global::PC.ServiceBus.Configuration.subscription();
        }
        #endregion
        
        #region Indexer
        /// <summary>
        /// Gets the <see cref="global::PC.ServiceBus.Configuration.subscription"/> at the specified index.
        /// </summary>
        /// <param name="index">The index of the <see cref="global::PC.ServiceBus.Configuration.subscription"/> to retrieve.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        public global::PC.ServiceBus.Configuration.subscription this[int index]
        {
            get
            {
                return ((global::PC.ServiceBus.Configuration.subscription)(base.BaseGet(index)));
            }
        }
        
        /// <summary>
        /// Gets the <see cref="global::PC.ServiceBus.Configuration.subscription"/> with the specified key.
        /// </summary>
        /// <param name="name">The key of the <see cref="global::PC.ServiceBus.Configuration.subscription"/> to retrieve.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        public global::PC.ServiceBus.Configuration.subscription this[object name]
        {
            get
            {
                return ((global::PC.ServiceBus.Configuration.subscription)(base.BaseGet(name)));
            }
        }
        #endregion
        
        #region Add
        /// <summary>
        /// Adds the specified <see cref="global::PC.ServiceBus.Configuration.subscription"/> to the <see cref="global::System.Configuration.ConfigurationElementCollection"/>.
        /// </summary>
        /// <param name="subscription">The <see cref="global::PC.ServiceBus.Configuration.subscription"/> to add.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        public void Add(global::PC.ServiceBus.Configuration.subscription subscription)
        {
            base.BaseAdd(subscription);
        }
        #endregion
        
        #region Remove
        /// <summary>
        /// Removes the specified <see cref="global::PC.ServiceBus.Configuration.subscription"/> from the <see cref="global::System.Configuration.ConfigurationElementCollection"/>.
        /// </summary>
        /// <param name="subscription">The <see cref="global::PC.ServiceBus.Configuration.subscription"/> to remove.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        public void Remove(global::PC.ServiceBus.Configuration.subscription subscription)
        {
            base.BaseRemove(this.GetElementKey(subscription));
        }
        #endregion
        
        #region GetItem
        /// <summary>
        /// Gets the <see cref="global::PC.ServiceBus.Configuration.subscription"/> at the specified index.
        /// </summary>
        /// <param name="index">The index of the <see cref="global::PC.ServiceBus.Configuration.subscription"/> to retrieve.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        public global::PC.ServiceBus.Configuration.subscription GetItemAt(int index)
        {
            return ((global::PC.ServiceBus.Configuration.subscription)(base.BaseGet(index)));
        }
        
        /// <summary>
        /// Gets the <see cref="global::PC.ServiceBus.Configuration.subscription"/> with the specified key.
        /// </summary>
        /// <param name="name">The key of the <see cref="global::PC.ServiceBus.Configuration.subscription"/> to retrieve.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        public global::PC.ServiceBus.Configuration.subscription GetItemByKey(string name)
        {
            return ((global::PC.ServiceBus.Configuration.subscription)(base.BaseGet(((object)(name)))));
        }
        #endregion
        
        #region IsReadOnly override
        /// <summary>
        /// Gets a value indicating whether the element is read-only.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        public override bool IsReadOnly()
        {
            return false;
        }
        #endregion
        
        #region name Property
        /// <summary>
        /// The XML name of the <see cref="name"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        internal const string namePropertyName = "name";
        
        /// <summary>
        /// Gets or sets the name.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        [global::System.ComponentModel.DescriptionAttribute("The name.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::PC.ServiceBus.Configuration.topic.namePropertyName, IsRequired=true, IsKey=true, IsDefaultCollection=false)]
        public virtual string name
        {
            get
            {
                return ((string)(base[global::PC.ServiceBus.Configuration.topic.namePropertyName]));
            }
            set
            {
                base[global::PC.ServiceBus.Configuration.topic.namePropertyName] = value;
            }
        }
        #endregion
        
        #region isEventBus Property
        /// <summary>
        /// The XML name of the <see cref="isEventBus"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        internal const string isEventBusPropertyName = "isEventBus";
        
        /// <summary>
        /// Gets or sets the isEventBus.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        [global::System.ComponentModel.DescriptionAttribute("The isEventBus.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::PC.ServiceBus.Configuration.topic.isEventBusPropertyName, IsRequired=false, IsKey=false, IsDefaultCollection=false)]
        public virtual bool isEventBus
        {
            get
            {
                return ((bool)(base[global::PC.ServiceBus.Configuration.topic.isEventBusPropertyName]));
            }
            set
            {
                base[global::PC.ServiceBus.Configuration.topic.isEventBusPropertyName] = value;
            }
        }
        #endregion
    }
}
